"""rename address

Revision ID: 11cf3cfa70ac
Revises: fdb0f0dacbf8
Create Date: 2024-04-01 23:41:43.674607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cf3cfa70ac'
down_revision = 'fdb0f0dacbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location', new_column_name='address')

    # ### end Alembic commands ###
