"""rename department

Revision ID: fdb0f0dacbf8
Revises: 26b05da88272
Create Date: 2024-04-01 20:07:13.000663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb0f0dacbf8'
down_revision = '26b05da88272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('departments')
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('departments')
    op.rename_table('departments','department')
    # ### end Alembic commands ###
